---
driver_plugin: vagrant

platforms:
- name: opscode-ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: true
  run_list:
  - recipe[apt]
- name: canonical-ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true

suites:
- name: standard
  run_list:
  - recipe[platform_packages]
  - recipe[test_setup]
  - recipe[orch_web]
  attributes:
    platform_packages:
      pkgs:
        - name: curl
- name: ssl
  run_list:
  - recipe[platform_packages]
  - recipe[test_setup::ssl]
  - recipe[orch_web]
  attributes:
    platform_packages:
      pkgs:
        - name: curl
